import * as THREE from 'three';
import {OrbitControls} from './assets/vendor/OrbitControls.js';
const $=s=>document.querySelector(s), video=$('#source-video'),canvas=$('#compare-canvas'),ctx=canvas.getContext('2d');
const cuts=[.25,.5,.75], dividers=[...document.querySelectorAll('.divider')],labels=[...document.querySelectorAll('#method-labels span')];
let scenes=[],selected='',meshData=null,meshMeta=null,loadToken=0,lastSample=-1,lastMethod='',activeAbort=null,playing=false;
function layoutCuts(){const bounds=[0,...cuts,1];dividers.forEach((d,i)=>{d.style.left=`${cuts[i]*100}%`;d.setAttribute('aria-valuenow',Math.round(cuts[i]*100));d.setAttribute('aria-valuemin',Math.round((i?cuts[i-1]+.04:.04)*100));d.setAttribute('aria-valuemax',Math.round((i<2?cuts[i+1]-.04:.96)*100));});labels.forEach((l,i)=>{l.style.left=`${(bounds[i]+bounds[i+1])*50}%`;});drawVideo();}
function moveCut(i,x){cuts[i]=Math.max(i?cuts[i-1]+.045:.045,Math.min(i<2?cuts[i+1]-.045:.955,x));layoutCuts();}
dividers.forEach((d,i)=>{d.addEventListener('pointerdown',e=>{d.setPointerCapture(e.pointerId);d.dataset.drag='1';});d.addEventListener('pointermove',e=>{if(d.dataset.drag==='1'){const r=$('#compare').getBoundingClientRect();moveCut(i,(e.clientX-r.left)/r.width);}});for(const name of ['pointerup','pointercancel','lostpointercapture'])d.addEventListener(name,()=>delete d.dataset.drag);d.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();moveCut(i,e.key==='Home'?0:e.key==='End'?1:cuts[i]+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?.05:.01));}});});
function drawVideo(){if(video.readyState<2)return;const bounds=[0,...cuts,1],w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);for(let i=0;i<4;i++){const sx=(i%2)*518,sy=Math.floor(i/2)*378;ctx.save();ctx.beginPath();ctx.rect(bounds[i]*w,0,(bounds[i+1]-bounds[i])*w+1,h);ctx.clip();ctx.drawImage(video,sx,sy,518,378,0,0,w,h);ctx.restore();}}
layoutCuts();
let renderer,scene,camera,controls,handGroup,grid;const objects=[];const world=$('#world-view');let renderAvailable=true;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xf1f3ee);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;world.replaceChildren(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.001,100);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.1;scene.add(new THREE.HemisphereLight(0xffffff,0x738575,2.4));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(1,-2,4);scene.add(key);const fill=new THREE.DirectionalLight(0xd8ebff,1.4);fill.position.set(-2,1,1);scene.add(fill);handGroup=new THREE.Group();scene.add(handGroup);const resize=()=>{const r=world.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(world);resize();renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#load-status').textContent='3D context interrupted — reload to restore';});}catch(e){renderAvailable=false;world.innerHTML='<p class="world-fallback">Interactive 3D requires WebGL. The video comparison remains available.</p>';}
function clearMeshes(){objects.forEach(pair=>pair.forEach(m=>{handGroup.remove(m);m.geometry.dispose();m.material.dispose();}));objects.length=0;}
function setupMeshes(){if(!renderAvailable||!meshMeta)return;clearMeshes();const method=$('#world-method').value,meta=meshMeta.methods[method];for(let age=0;age<7;age++){const pair=[];for(let side=0;side<2;side++){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(meta.vertices*3),3));g.setIndex(meta.faces[side].flat());const mat=new THREE.MeshStandardMaterial({color:0x377e9b,roughness:.65,metalness:0,side:THREE.DoubleSide});const m=new THREE.Mesh(g,mat);m.visible=false;handGroup.add(m);pair.push(m);}objects.push(pair);}lastSample=-1;lastMethod=method;updateHands(true);}
function resetView(){if(!renderAvailable||!meshMeta)return;const m=meshMeta.methods.Ours,center=new THREE.Vector3(...m.min).add(new THREE.Vector3(...m.scale).multiplyScalar(.5));const span=Math.max(...m.scale,.3);camera.position.copy(center).add(new THREE.Vector3(1.1,-1.65,1.0).multiplyScalar(span));camera.up.set(0,0,1);camera.near=.001;camera.far=Math.max(100,span*30);camera.updateProjectionMatrix();controls.target.copy(center);controls.minDistance=span*.15;controls.maxDistance=span*12;controls.update();if(grid){scene.remove(grid);grid.geometry.dispose();grid.material.dispose();}grid=new THREE.GridHelper(span*2.5,12,0xc3ccbf,0xdfe4da);grid.rotation.x=Math.PI/2;grid.position.copy(center);grid.position.z=m.min[2]-.025;scene.add(grid);}
function updateHands(force=false){if(!meshData||!meshMeta||!renderAvailable)return;const method=$('#world-method').value;if(method!==lastMethod){setupMeshes();return;}const idx=Math.min(meshMeta.frames-1,Math.floor(video.currentTime*3+1e-5));if(idx===lastSample&&!force)return;lastSample=idx;const meta=meshMeta.methods[method],quant=new Uint16Array(meshData,meta.offset,meta.byteLength/2);const newest=new THREE.Color(method==='Ours'?0x277593:0xab4e40),oldest=new THREE.Color(method==='Ours'?0xe0eded:0xf1e5df);for(let age=0;age<7;age++){const f=idx-age;for(let side=0;side<2;side++){const obj=objects[age][side];obj.visible=f>=0&&meta.valid[f][side];if(!obj.visible)continue;const a=obj.geometry.attributes.position.array;const offset=(f*2+side)*meta.vertices*3;for(let k=0;k<a.length;k++)a[k]=meta.min[k%3]+quant[offset+k]/65535*meta.scale[k%3];obj.geometry.attributes.position.needsUpdate=true;obj.geometry.computeVertexNormals();obj.geometry.computeBoundingSphere();obj.material.color.copy(newest).lerp(oldest,age/6);}}world.dataset.sample=idx;world.dataset.visibleSamples=Math.min(idx+1,7);}
$('#world-method').addEventListener('change',setupMeshes);$('#reset-view').addEventListener('click',resetView);
function fmt(t){return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;}
function sync(){drawVideo();updateHands();if(Number.isFinite(video.duration)){$('#timeline').max=video.duration;$('#timeline').value=video.currentTime;$('#time').textContent=`${fmt(video.currentTime)} / ${fmt(video.duration)}`;}}
for(const e of ['loadeddata','seeked','timeupdate'])video.addEventListener(e,sync);
video.addEventListener('play',()=>{playing=true;$('#play').textContent='Ⅱ Pause';$('#play').setAttribute('aria-label','Pause comparison');});video.addEventListener('pause',()=>{playing=false;$('#play').textContent='▶ Play';$('#play').setAttribute('aria-label','Play comparison');});video.loop=true;
$('#play').addEventListener('click',async()=>{if(video.paused){try{await video.play();}catch(e){$('#load-status').textContent='Unable to play this video';}}else video.pause();});$('#timeline').addEventListener('input',e=>{video.currentTime=Number(e.target.value);});$('#loop').addEventListener('click',()=>{video.loop=!video.loop;$('#loop').setAttribute('aria-pressed',video.loop);$('#loop').textContent=video.loop?'Loop on':'Loop off';});
function animate(){requestAnimationFrame(animate);if(playing)sync();if(renderAvailable){controls.update();renderer.render(scene,camera);}}animate();
async function selectScene(item){selected=item.id;const token=++loadToken;video.pause();if(activeAbort)activeAbort.abort();activeAbort=new AbortController();const signal=activeAbort.signal;meshData=null;meshMeta=null;if(renderAvailable)clearMeshes();$('#scene-title').textContent=`${item.dataset} · ${item.title}`;$('#load-status').textContent='Loading video & 3D…';$('#time').textContent='0:00 / 0:00';$('#timeline').value=0;document.querySelectorAll('.scene-card').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===item.id));ctx.clearRect(0,0,canvas.width,canvas.height);video.src=`assets/videos/${item.id}.mp4`;video.load();try{const responses=await Promise.all([fetch(`assets/world/${item.id}/mesh.json`,{signal}),fetch(`assets/world/${item.id}/mesh.bin`,{signal})]);if(responses.some(r=>!r.ok))throw Error('asset unavailable');const [meta,data]=await Promise.all([responses[0].json(),responses[1].arrayBuffer()]);if(token!==loadToken)return;meshMeta=meta;meshData=data;setupMeshes();resetView();sync();$('#load-status').textContent='3 poses / second · 7-frame history';window.infinihandStatus={scene:item.id,meshFrames:meta.frames,methods:Object.keys(meta.methods),loaded:true};}catch(e){if(e.name==='AbortError')return;$('#load-status').textContent='3D could not load. Select scene to retry.';console.error(e);}}
try{const r=await fetch('assets/scenes.json');scenes=await r.json();const picker=$('#scene-picker');for(const item of scenes){const button=document.createElement('button');button.className='scene-card';button.dataset.id=item.id;button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',`${item.dataset}: ${item.title}`);button.innerHTML=`<img src="assets/videos/${item.id}.jpg" alt="" loading="lazy"><small>${item.dataset}</small><b>${item.title}</b>`;button.addEventListener('click',()=>selectScene(item));picker.append(button);}await selectScene(scenes[0]);}catch(e){$('#load-status').textContent='Could not load scenes. Please reload.';console.error(e);}

$('#copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#bibtex').textContent);$('#copy-status').textContent='Citation copied.';}catch{$('#copy-status').textContent='Select and copy the BibTeX above.';}});
